// Burada yıldız gemilerinin isim ve modelleri yer almaktadır. İnput alanına bir şey yazdığımızda bu liste içinde filtere işlemi yapılmaktadır.

const starships = [
  "CR90 corvette",
  "Star Destroyer",
  "Imperial I-class Star Destroyer",
  "Sentinel-class landing craft",
  "Death Star",
  "DS-1 Orbital Battle Station",
  "Millennium Falcon",
  "YT-1300 Light Freighter",
  "Y-wing",
  "BTL Y-Wing",
  "X-wing",
  "T-65 X-Wing",
  "TIE Advanced x1",
  "Twin Ion Engine Advanced X1",
  "Executor",
  "Executor-Class Star Dreadnought",
  "Rebel transport",
  "GR-75 Medium Transport",
  "Slave 1",
  "Firespray-31-Class Patrol and Attack",
  "Imperial shuttle",
  "Lambda-Class T-4a Shuttle",
  "EF76 Nebulon-B escort frigate",
  "Calamari Cruiser",
  "MC80 Libery Type Star Cruiser",
  "A-wing",
  "RZ-1 A-Wing Interceptor",
  "B-wing",
  "A/SF-01 B-Wing Starfighter",
  "Republic Cruiser",
  "Consular-Class Cruiser",
  "Droid control ship",
  "Lucrehulk-Class Droid Control Ship",
  "Naboo fighter",
  "N-1 Starfighter",
  "Naboo Royal Starship",
  "J-Type 327 Nubian Royal Starship",
  "Scimitar",
  "Star Courier",
  "J-type diplomatic barge",
  "AA-9 Coruscant freighter",
  "Botajef AA-9 Freighter-Liner",
  "Jedi starfighter",
  "Delta-7 Aethersprite-Class Interceptor",
  "H-type Nubian yacht",
  "Republic Assault ship",
  "Acclamator I-Class Assault Ship",
  "Solar Sailer",
  "Punworcca 116-Class Interstellar Sloop",
  "Trade Federation cruiser",
  "Providence-Class Carrier/Destroyer",
  "Theta-class T-2c shuttle",
  "Republic attack cruiser",
  "Senator-Class Star Destroyer",
  "Naboo star skiff",
  "J-Type Star Skiff",
  "Jedi Interceptor",
  "Eta-2 Actis-Class Light Interceptor",
  "Arc-170",
  "Aggressive Reconnaissance-170 Starfighter",
  "Banking clan frigte",
  "Munificent-Class Star Frigate",
  "Belbullab-22 starfighter",
  "V-wing",
  "Alpha-3 Nimbus-Class V-Wing Starfighter",
];

export default starships;
